# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A blog about programming and productivity
email: RanjitSaini@codehealthy.com
baseurl: "" # the subpath of your site, e.g. /blog
url: https://codehealthy.com
twitter_username: king99immortal
github_username:  1nsp1r3rnzt
name: "Ranjit Singh"
description: "A Blog about programming"
teaser: /assets/images/500x300.png
#breadcrumbs: false  # disabled by default and beta feature
search: true
permalink: /:title/
title_separator: "&#124;"
#pagination
paginate: 5 # amount of posts to show
paginate_path: /page:num/

#twitter and facebook
twitter:
  username: "king99immortal"

facebook:
  username: "codehealthy"


collections_dir: all_collections

collections:
  podcasts:
    output: true
    permalink: /:collection/:slug/
  notes:
    output: true
    permalink: /:collection/:path/
  podcastepisodes:
    output: true
    permalink: /podcasts/:path/
  books:
    output: true
    permalink: /:collection/:path/
#social google
social:
  type:  # Person or Organization (defaults to Person)
  name: "Ranjit Singh"
  links:
    - "https://twitter.com/king99immortal"
    - "https://facebook.com/codehealthy.com"
    - "https://www.linkedin.com/in/ranjitsinghsaini"
   # - "https://plus.google.com/your_profile"

#author for left sidebar
author:
  name   : "Ranjit Singh"
  avatar : "/assets/images/pic.jpg"
  bio    : "An enthusiastic Software Developer by day<br> Blogger by night"
  email  : "ranjitsaini@codhealthy.com"
  uri    : 
  home   : "https://codehealthy.com"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : codehealthy
  foursquare       :
  github : 1nsp1r3rnzt
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : ranjitsinghsaini
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          : "king99immortal"
  vine             :
  weibo            :
  xing             :
  youtube          :  "https://www.youtube.com/channel/UCaOvOWi2sBTD-i2RBFz8HhA"



#fb fallback image min 120px by 120px and < 1mb
og_image: /assets/images/500x300.png



#disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "codehealthy-com"

#defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: true
      layout: single
      author_profile: true
      share: true
      related: true
 
  - scope:
      path: ""
      type: "books"
    values:
      layout: single
      classes: "wide"
      author_profile: false
      share: true
      collection_type: "books"

  - scope:
      path: ""
      type: "podcastepisodes"
    values:
      collection_type: "podcasts"
      share: true
      comments: true

include:
  - .htaccess
  - _pages
  



# _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

#
category_default_thumbnail:
  Android: "/assets/images/fallback/Android.png"
  books: "/assets/images/fallback/books.jpg"
  programming: "/assets/images/fallback/programming.png"

#categories and tags
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

#compress
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-gist


head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   

exclude:
   - otherpages
   - deploy   

